name: Deploy HTML to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ðŸ”¹ Necesario para Vitest
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host *\n  StrictHostKeyChecking no\n  IdentitiesOnly yes" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      # TESTS
      - name: Deploy via SCP (with tests)
        run: |
          set -e

          echo "Ejecutando tests unitarios..."
          npx vitest run --reporter=verbose

          echo "Tests OK, desplegando..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "rm -rf /var/www/alumnos/${{ secrets.USERNAME }}/*"

          scp -o StrictHostKeyChecking=no -r ./ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/alumnos/${{ secrets.USERNAME }}/
