name: Deploy Vue to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test
        # ðŸ‘‰ Si algÃºn test falla:
        # - este paso falla
        # - el job se detiene
        # - NO hay build
        # - NO hay deploy

      - name: Build Vue
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host *\n  StrictHostKeyChecking no\n  IdentitiesOnly yes" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Clean dist folder on server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
          "rm -rf /var/www/alumnos/${{ secrets.USERNAME }}/dist/*"

      - name: Deploy dist via SCP
        run: |
          scp -r dist/* \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/alumnos/${{ secrets.USERNAME }}/dist/
